---
name: Prisma Cloud Checkov Scan and Upload

on:
  pull_request: {}
  push:
    branches:
      - main
      - master

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Prisma Cloud Checkov
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: ${{ vars.PRISMA_URL }}
        with:
          api-key: ${{ secrets.PRISMA_USERNAME }}::${{ secrets.PRISMA_PASSWORD}}
